import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View, Dimensions, Modal, ScrollView, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { MotiView, MotiText } from 'moti';
import { AuraBackground } from '@/components/AuraBackground';
import { COLORS } from '@/constants/theme';
import { LinearGradient } from 'expo-linear-gradient';
import { Image } from 'react-native';
import { useAuraContext } from '@/context/AuraContext';
import { LucideHistory, LucideX, LucideSparkles } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const { width } = Dimensions.get('window');

const DISCLAIMER_SL = `POGOJI UPORABE IN OMEJITEV ODGOVORNOSTI

Solaura AI je aplikacija za zabavo in osebno refleksijo. Vse vsebine, napovedi, analize in "branja avre", ki jih ustvari umetna inteligenca, so namenjene IZKLJUČNO v zabavne namene.

⚠️ NI STROKOVNI NASVET
Vsebine v aplikaciji NE predstavljajo strokovnega medicinskega, psihološkega, finančnega, pravnega ali kakršnega koli drugega svetovanja. Nobene vsebine ne smete razlagati kot diagnozo, zdravniški nasvet, finančno priporočilo ali napotitev k strokovnjaku.

🔮 ZABAVA, NE RESNIČNOST
Napovedi in "branja" so ustvarjena z umetno inteligenco in so izmišljene ter simbolične narave. Solaura AI ne trdi, da ima nadnaravne sposobnosti, ne napoveduje prihodnosti z gotovostjo in ne zagotavlja točnosti katerih koli rezultatov.

📸 ZASEBNOST IN PODATKI
Slike vašega obraza se v živo obdelajo prek OpenAI API in se ne shranjujejo trajno na naše strežnike. Za analizo se uporablja API tretje osebe (OpenAI), ki deluje v skladu z lastnimi pogoji zasebnosti (openai.com/privacy).

👤 VAŠA ODGOVORNOST
Z uporabo aplikacije potrjujete, da ste starejši od 13 let in da vse vsebine jemljete izključno kot zabavo. Za morebitne odločitve, ki bi jih sprejeli na podlagi vsebine aplikacije, ste odgovorni sami.

💛 ČUSTVENA DOBROBIT
Če ste v stiski, prosimo, poiščite pomoč pri ustreznih strokovnjakih. Solaura AI ne nadomešča strokovne psihološke ali medicinske pomoči.

Prosta za osebno, nekomercialno uporabo. Vsa pravice pridržane © 2025 Solaura AI.`;

const DISCLAIMER_EN = `TERMS OF USE & DISCLAIMER

Solaura AI is an entertainment and personal reflection application. All content, predictions, analyses, and "aura readings" generated by artificial intelligence are intended for ENTERTAINMENT PURPOSES ONLY.

⚠️ NOT PROFESSIONAL ADVICE
Content within this application does NOT constitute professional medical, psychological, financial, legal, or any other form of advice. Nothing should be interpreted as a diagnosis, medical advice, financial recommendation, or referral to a specialist.

🔮 ENTERTAINMENT, NOT REALITY
Predictions and "readings" are generated by AI and are fictional and symbolic in nature. Solaura AI does not claim supernatural abilities, does not predict the future with certainty, and does not guarantee the accuracy of any results.

📸 PRIVACY & DATA
Your facial images are processed in real-time via the OpenAI API and are not permanently stored on our servers. Analysis uses a third-party API (OpenAI) operating under its own privacy terms (openai.com/privacy).

👤 YOUR RESPONSIBILITY
By using this application, you confirm that you are over 13 years old and that you treat all content purely as entertainment. You are solely responsible for any decisions made based on the app's content.

💛 EMOTIONAL WELLBEING
If you are in distress, please seek help from appropriate professionals. Solaura AI does not replace professional psychological or medical support.

Free for personal, non-commercial use. All rights reserved © 2025 Solaura AI.`;

export default function HookScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { t, i18n: i18nBase } = useTranslation();
  const { triggerHaptic } = useAuraContext();
  const [disclaimerOpen, setDisclaimerOpen] = useState(false);

  const sl = i18nBase.language?.startsWith('sl');

  const changeLanguage = (lng: string) => {
    triggerHaptic('light');
    i18nBase.changeLanguage(lng);
  };

  return (
    <>
      <AuraBackground>
        <View style={styles.container}>
          {/* Language switcher - top center, slim */}
          <MotiView
            from={{ opacity: 0, translateY: -20 }}
            animate={{ opacity: 1, translateY: 0 }}
            transition={{ type: 'timing', delay: 300 }}
            style={styles.langRow}
          >
            <TouchableOpacity
              onPress={() => changeLanguage('sl')}
              style={[styles.langBtn, i18nBase.language === 'sl' && styles.langBtnActive]}
            >
              <Text style={[styles.langBtnText, i18nBase.language === 'sl' && styles.langBtnTextActive]}>SLO</Text>
            </TouchableOpacity>
            <View style={styles.langDivider} />
            <TouchableOpacity
              onPress={() => changeLanguage('en')}
              style={[styles.langBtn, i18nBase.language === 'en' && styles.langBtnActive]}
            >
              <Text style={[styles.langBtnText, i18nBase.language === 'en' && styles.langBtnTextActive]}>ENG</Text>
            </TouchableOpacity>
          </MotiView>

          {/* Logo centered */}
          <MotiView
            from={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ type: 'timing', duration: 2000 }}
            style={styles.logoWrapper}
          >
            <Image
              source={require('../../assets/images/icon.png')}
              style={styles.logoImage}
              resizeMode="cover"
            />
          </MotiView>

          {/* Bottom content */}
          <View style={[styles.bottomContent, { paddingBottom: insets.bottom + 10 }]}>
            <MotiText
              from={{ opacity: 0, translateY: 30 }}
              animate={{ opacity: 1, translateY: 0 }}
              transition={{ type: 'timing', delay: 800, duration: 1000 }}
              style={styles.title}
            >
              {t('welcome')}
            </MotiText>

            {/* Main CTA */}
            <MotiView
              from={{ opacity: 0, translateY: 20 }}
              animate={{ opacity: 1, translateY: 0 }}
              transition={{ type: 'timing', delay: 1200, duration: 800 }}
            >
              <TouchableOpacity
                activeOpacity={0.85}
                onPress={() => { triggerHaptic('medium'); router.push('/onboarding'); }}
                style={styles.ctaWrapper}
              >
                <LinearGradient
                  colors={['#BF953F', '#FCF6BA', '#AA771C']}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                  style={styles.cta}
                >
                  <Text style={styles.ctaText}>{t('start_scan')}</Text>
                </LinearGradient>
              </TouchableOpacity>
            </MotiView>

            {/* Secondary links below CTA */}
            <MotiView
              from={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ type: 'timing', delay: 1600 }}
              style={styles.historyRow}
            >
              <TouchableOpacity
                onPress={() => { triggerHaptic('light'); router.push('/cosmos'); }}
                style={styles.historyBtn}
              >
                <LucideSparkles color={COLORS.secondary} size={16} />
                <Text style={styles.historyText}>{sl ? 'Kozmos' : 'Cosmos'}</Text>
              </TouchableOpacity>

              <View style={{ width: 1, height: 20, backgroundColor: 'rgba(255,255,255,0.2)', marginHorizontal: 20 }} />

              <TouchableOpacity
                onPress={() => { triggerHaptic('light'); router.push('/history'); }}
                style={styles.historyBtn}
              >
                <LucideHistory color={COLORS.secondary} size={16} />
                <Text style={styles.historyText}>{t('history_title')}</Text>
              </TouchableOpacity>
            </MotiView>

            {/* Fine print disclaimer link */}
            <MotiView
              from={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ type: 'timing', delay: 2000 }}
            >
              <TouchableOpacity onPress={() => setDisclaimerOpen(true)} style={styles.finePrintBtn}>
                <Text style={styles.finePrintText}>
                  {sl ? 'Pogoji uporabe' : 'Terms of Use'}
                </Text>
              </TouchableOpacity>
            </MotiView>
          </View>
        </View>
      </AuraBackground>

      {/* ── DISCLAIMER MODAL ── */}
      <Modal
        visible={disclaimerOpen}
        transparent={true}
        animationType="slide"
        onRequestClose={() => setDisclaimerOpen(false)}
      >
        <View style={styles.modalOverlay}>
          <TouchableOpacity 
            style={StyleSheet.absoluteFillObject} 
            activeOpacity={1} 
            onPress={() => setDisclaimerOpen(false)} 
          />
          <View style={[styles.modalCard, { paddingBottom: Math.max(80, (insets?.bottom || 0) + 40) }]}>
            {/* Handle */}
            <View style={styles.modalHandle} />

            {/* Header */}
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>
                {sl ? '⚖️ Pogoji uporabe' : '⚖️ Terms of Use'}
              </Text>
              <TouchableOpacity onPress={() => setDisclaimerOpen(false)} style={styles.closeBtn}>
                <LucideX color="#FFF" size={20} />
              </TouchableOpacity>
            </View>

            <View style={styles.entertainmentBadge}>
              <Text style={styles.entertainmentText}>
                {sl ? 'ℹ️ AI NAPOVEDI SO SIMBOLIČNE NARAVE' : 'ℹ️ AI PREDICTIONS ARE SYMBOLIC IN NATURE'}
              </Text>
            </View>

            <ScrollView
              style={styles.scrollArea}
              showsVerticalScrollIndicator={false}
              contentContainerStyle={{ paddingBottom: 20 }}
            >
              <Text style={styles.disclaimerText}>
                {sl ? DISCLAIMER_SL : DISCLAIMER_EN}
              </Text>
            </ScrollView>

            <TouchableOpacity
              onPress={() => setDisclaimerOpen(false)}
              style={styles.closeFooterBtn}
            >
              <Text style={styles.closeFooterText}>
                {sl ? 'Potrjujem in soglašam ✓' : 'Confirm & Agree ✓'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  langRow: {
    position: 'absolute',
    top: 60,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 30,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.15)',
  },
  langBtn: {
    paddingHorizontal: 22,
    paddingVertical: 9,
    borderRadius: 25,
  },
  langBtnActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
  },
  langBtnText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
  },
  langBtnTextActive: {
    color: '#D4AF37',
  },
  langDivider: {
    width: 1,
    height: 15,
    backgroundColor: 'rgba(212, 175, 55, 0.3)',
  },
  logoWrapper: {
    position: 'absolute',
    top: '15%',
    alignItems: 'center',
  },
  logoImage: {
    width: 240,
    height: 240,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: 'rgba(212, 175, 55, 0.2)',
  },
  bottomContent: {
    position: 'absolute',
    bottom: 25,
    left: 24,
    right: 24,
    gap: 16,
    alignItems: 'center',
  },
  title: {
    fontSize: 40,
    fontWeight: '300',
    color: '#FFF',
    textAlign: 'center',
    lineHeight: 50,
    letterSpacing: 1,
    marginBottom: 4,
  },
  ctaWrapper: {
    borderRadius: 99,
    overflow: 'hidden',
    width: width - 48,
  },
  cta: {
    paddingVertical: 22,
    alignItems: 'center',
  },
  ctaText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2.5,
    textTransform: 'uppercase',
  },
  historyRow: {
    alignItems: 'center',
  },
  historyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.2)',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  historyText: {
    color: COLORS.secondary,
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 1,
  },
  finePrintBtn: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 8,
  },
  finePrintText: {
    color: 'rgba(255,255,255,0.25)',
    fontSize: 11,
    letterSpacing: 0.5,
    textAlign: 'center',
    textDecorationLine: 'underline',
    textDecorationColor: 'rgba(255,255,255,0.15)',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#0E0720',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 50,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.15)',
    borderBottomWidth: 0,
    width: '100%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: COLORS.secondary,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.07)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  entertainmentBadge: {
    backgroundColor: 'rgba(212,175,55,0.1)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.25)',
    marginBottom: 16,
  },
  entertainmentText: {
    color: COLORS.secondary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  scrollArea: {
    flexShrink: 1,
    marginBottom: 16,
  },
  disclaimerText: {
    color: '#E0E0E0',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  closeFooterBtn: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.2)',
  },
  closeFooterText: {
    color: COLORS.secondary,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 1,
  },
});
